### ISSUE TITLE
vue3: vue-template-compiler must be installed as a peer dependency

### ISSUE THREAD

**Issue by dspangenberg** [MMF-FE/svgicon#130]
Hi,

if I use 

`transformAssetUrls: {
        [tagName]: ['data'],
    },`

in .vue-svgicon.config.js like in the demo/vue-demo/.vue-svgicon.config in the documentation, I get the following errors:

```
Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.

Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.

Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/dspangenberg/Projects/myra/test/node_modules/@vue/component-compiler-utils/dist/parse.js:15:23)
    at Object.module.exports (/Users/dspangenberg/Projects/myra/test/node_modules/vue-loader/lib/index.js:67:22)
```

**.vue-svgicon.config.js**
```
const path = require('path')
const svgFilePaths = ['./src/assets/svgs'].map((v) => path.resolve(v))
const tagName = 'icon'

module.exports = {
  tagName,
  svgFilePath: svgFilePaths,
  svgoConfig: {},
  pathAlias: {
    '@icon': svgFilePaths[0]
  },
  transformAssetUrls: {
    [tagName]: ['data'],
  }
}
```

**Vue.config.js:**
```
module.exports = {
  runtimeCompiler: true
}
```

**Comment by Allenice** [comment]
If you want to use transformAssetUrls, please upgrade vue-loader to v16+
```bash
yarn add vue-loader@next --dev
```
